### ISSUE TITLE
Access to accum function

### ISSUE THREAD

**Issue by jperkelens** [rbrush/clara-rules#137]
Was trying to build a custom accumulator, and am having troble getting access to the accum function.

When i put (:require [clara.rules.accumulators :as acc]) in my project i get access to the predefined accumulators but not the accum function to define my own. Is there something else i need to be doing?

**Comment by jperkelens** [comment]
Just noticed that accum was committed 15 days ago, whereas 0.8.9 was published in late September, which explains it. Do you plan on pushing a new version soon or Is there a RC version i can use? it would be really helpful.

**Comment by rbrush** [comment]
Yes, I published the 0.9 API doc prematurely with a 0.8.9 label. My mistake! I am planning on doing a release of 0.9 this week, but I just published a snapshot build to the Sonatype repository, so you can change your Clara dependency to this:

```clj
[org.toomuchcode/clara-rules "0.9.0-SNAPSHOT"]
```

And add the following to your project.clj.

```clj
  :repositories [["snapshots" {:url "https://oss.sonatype.org/content/repositories/snapshots/"}]]
```

Of course, the the Maven equivalents will work as well. Sorry for the confusion!

**Comment by jperkelens** [comment]
Great thanks so much for yr quick response and this great tool.

**Comment by rbrush** [comment]
clara-rules 0.9 is out and available on Clojars, so you can move away from that snapshot build. Details in the release announcement here: https://groups.google.com/forum/#!topic/clara-rules/6Y2zHx9OQwA.

I'm closing this since there isn't anything more to do here. If you have any further topics, I keep an eye on the Clara google group (https://groups.google.com/forum/#!forum/clara-rules) and am happy to follow up there.

**Comment by rbrush** [comment]
Apparently I forgot to close this. Doing so now. ;)
