### ISSUE TITLE
Release 0.9.1 on clojars?

### ISSUE THREAD

**Issue by arnaudbos** [rbrush/clara-rules#143]
Hi, first of all, thank you for this excellent work!

I was wondering if version 0.9.1 could be released on Clojars as I see the milestone 0.9.1 is 100% complete.

I would need the fix for issue #142 which is marked as resolved in it. I've tested my use case against 0.10.0-SNAPSHOT locally (just a few minutes ago) and it works very well.

Thanks.

**Comment by rbrush** [comment]
Sure, I'll release 0.9.1 (essentially the current 0.10.0-SNAPSHOT) within the next day or so. It's been on the to-do list, so I just needed a nudge. ;)

I'll post back here when it's available.

**Comment by rbrush** [comment]
0.9.1 is up on Clojars! Details of the release are in the changeling, but it's basically just issue #142 and another change that supports it.

https://github.com/rbrush/clara-rules/blob/master/CHANGELOG.md#091

Closing the issue since there is nothing more to do, but we can reopen or create a new issue if anything comes up.
