### ISSUE TITLE
Improve the efficiency of compiling the expressions.

### ISSUE THREAD

**Issue by ylando2** [rbrush/clara-rules#153]
Hello Ryan,

You have a function to-dnf, that "Convert a lhs expression to disjunctive normal form." the problem with this is that the normal form could get exponential large consider the expression:
(and (or a1 a2 a3) (or b1 b2 b3) (or c1 c2 c3) ...)
Will turn into:
(or (and a1 b1 c1) (and a1 b2 c1) (and a1 b3 c1)  (and a1 b1 c2) ...)
If you have n subexpression with m element in every group you will get n^m expression in the disjunctive normal form. The real reta network only needs n*m nodes:
a1,a2,a3 connect to b1,b2,b3 and b1,b2,b3 connect to c1,c2,c3.
There are two possible ways to improve the efficiency of compiling the expressions.
1) We can remove this function and create the reta network directly.
2) My pull request about "cartesian-join" turn the exponential expression return from to-dnf into polynomial expression by reusing the expressions. We can use memoization between expression and  node on the tree to reduce the computation.

Regards,
Yuval

**Comment by rbrush** [comment]
Hey, thanks for looking into this.

The explosion of expressions created in to-dnf should be unified when building the rete network itself. ```to-dnf``` just focuses on the single goal of converting the expression to disjunctive normal form, but there is an additional step to unify those expressions when building the rete network. If you call clara.rules.compiler/to-beta-tree on a sequence of rules, it will return a tree structure representing the beta side of the network. As part of creating that structure it will merge matching expressions, eliminating redundancy. At least some of the explosion of expressions in ```to-dnf``` is removed there.

There are probably further opportunities to optimize the beta side of the network. However, I don't think this logic belongs in to-dnf, because we want to merge logic from separate rules as well. So if someone has separate rules of the form (and a1 b1 c1) (and a1 b2 c1), etc, then these would not be merged in to-dnf, but in an optimization of to-beta-tree (or a function that it calls, like add-to-beta-tree).

I often use to-beta-tree to inspect and debug the structure of the actual generated rete network. A test that calls to-beta-tree for some set of rules and demonstrates a surprising or poorly optimized structure is probably a good start to expose an optimization bug here. If you have an example test that shows a surprising beta tree and are able to post it, I'd be happy to look for ways we can improve it.

**Comment by ylando2** [comment]
Maybe you optimize the beta tree, but the question is do you optimize the work to create the beta tree?
If you parse every expression you still do exponential work. You can reduce the compiler work by creating a map between expressions and node on the beta tree. Creating a hash for every expression can still be heavy so we can add an ID for every expression and at least reduce the work of parsing the result of cartesian-join.

For testing I try to run the following code and it does not complete the computation.
```clojure
(defrecord Success [])
(defrecord Fact [a1 a2 a3 a4 a5 a6 a7 a8 a9 a10 a11 a12 a13 a14 a15 a16 a17 a18 a19 a20])
(defrule exponential
     "Forcing the compiler to do exponential work"
	 (and (or [Fact (= :a1 1)] [Fact (= :a1 2)]) (or [Fact (= :a2 1)] [Fact (= :a2 2)]) (or [Fact (= :a3 1)] [Fact (= :a3 2)]) (or [Fact (= :a4 1)] [Fact (= :a4 2)]) (or [Fact (= :a5 1)] [Fact (= :a5 2)]) (or [Fact (= :a6 1)] [Fact (= :a6 2)]) (or [Fact (= :a7 1)] [Fact (= :a7 2)]) (or [Fact (= :a8 1)] [Fact (= :a8 2)]) (or [Fact (= :a9 1)] [Fact (= :a9 2)]) (or [Fact (= :a10 1)] [Fact (= :a10 2)]) (or [Fact (= :a11 1)] [Fact (= :a11 2)]) (or [Fact (= :a12 1)] [Fact (= :a12 2)]) (or [Fact (= :a13 1)] [Fact (= :a13 2)]) (or [Fact (= :a14 1)] [Fact (= :a14 2)]) (or [Fact (= :a15 1)] [Fact (= :a15 2)]) (or [Fact (= :a16 1)] [Fact (= :a16 2)]) (or [Fact (= :a17 1)] [Fact (= :a17 2)]) (or [Fact (= :a18 1)] [Fact (= :a18 2)]) (or [Fact (= :a19 1)] [Fact (= :a19 2)]) (or [Fact (= :a20 1)] [Fact (= :a20 2)]))
	 =>
	 (insert! (->Success)))
(def s (mk-session))
```

**Comment by rbrush** [comment]
Ah, thanks for the test case. I hadn't been worried about to-dnf since it is only used in creating the (typically cached) session, but this demonstrates unacceptable performance for rules this complicated. Apologies for being a bit slow on the uptake!

I'll want to poke around a performance analyzer to get a better idea of where we spend our time here. We may be able to take advantage of the fact that many of the expressions produced by to-dnf are identical (in context of Clojure's (identitical?) function). 

I don't think we can completely get rid of the exponential growth, since this is something of a worst-case scenario for rete, but we can at least optimize it.

**Comment by rbrush** [comment]
I created a branch to work through for this here: https://github.com/rbrush/clara-rules/compare/issue-153

The content in that branch focus on creating disjunctive normal form for the exponential example @ylando2  posted above. Right now it includes the cartesian-join optimization and also optimizes to-dnf itself. These changes are showing a 20x performance improvement for creating this very large DN operation on my machine, bringing the time here down to reasonable levels.

Here are some runs without
```
(time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 19144.978817 msecs"
1048577
(time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 18843.939992 msecs"
1048577
(time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 18629.343022 msecs"
1048577
```

And runs with the optimization:

```
time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 875.812601 msecs"
1048577
(time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 885.280799 msecs"
1048577
(time (count (clara.rules.compiler/to-dnf (first (:lhs exponential)))))
"Elapsed time: 872.494891 msecs"
1048577
```

There is still more to do in the engine before such a huge disjunction can be used. The to-beta-tree implementation is not efficient for this many nodes and should be built using transients, then converted to its final form. It can also possibly do a better job of eliminating further redundancy in the disjunctive normal form.

**Comment by mrrodriguez** [comment]
I'll just comment here now for anything on this topic instead of on https://github.com/rbrush/clara-rules/pull/154.
`cartesian-join` changes look pretty good.  I think it is definitely more readable and more efficient without the redundant recursion issues discussed previously.

There is a lot of lazy evaluation and persistent data structures being used in these steps of the beta tree, including this `to-dnf` logic, which could be overhead - but like Ryan has already said previously - I'd like to see concrete areas where performance would warrant the use of transient structures or other mutable variants.  

It is likely there are hot spots that would benefit from this.  Another thought that comes to mind is that we could be utilizing transducers more in many of these places if we found them to be helpful.  They can certainly cause a lot less thrash of allocating intermediary collections, as well avoid lazy evaluation overhead when we eagerly consume the structure immediately anyways.

**Comment by rbrush** [comment]
The above commit is enormous, but it should address this particular issue and make future optimizations to the beta network much simpler. In a nutshell, I made two significant changes:

* Changed the data model used to build the beta side of the network to use nodes and a separate collection of edge relationships. This is a lot easier and more efficient to manipulate and view when contrasted to the deep tree used previously.
* Rather than converting the entire rule to disjunctive normal form, I'm now converting each top-level conjunction to DNF and wiring them together as we go. So rather than the exponential explosion across all forms, each top-level item has its own beta network that we incorporate as we go.

I ran the example @ylando2 had posted, and it now completes quickly.

This change is big enough that I'm going to target it for a 0.10.0 release rather than 0.9.3. I don't think external code directly uses the beta graph data model, and all tests continue to work, but it's possible that  this changes the order rules fire (which isn't defined but users could be relying on) or similar things.

The good news is this change did not touch clara.rules.engine at all...it's really an optimization on how we assemble the network.

Anyway, I want to run some more test cases and review these changes again before merging them to master, but I'm sharing here in case anyone is interested.

**Comment by mrrodriguez** [comment]
Wow!  This is quite a change/uplift.  I scanned through it on a fairly high-level and I think it is looking pretty good.  It seems a bit easier to follow perhaps too.  I'm curious to play around with it now and see if I find anything or see any positive results on the performance side etc.

**Comment by rbrush** [comment]
I rebased these changes and merged into master in the above commits. I'm going to go ahead and close this in preparation for a 0.10.0 release, and we can open separate issues for any additional optimizations.
