### ISSUE TITLE
Facts under a binding group can cause an accumulator with an initial value to have downstream results even after retraction

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#189]
I'd expect the following test to pass:

````
(deftest test-accum-all-with-bindings
  (let [mci-temps [(->Temperature 10 "MCI")
                   (->Temperature 20 "MCI")]
        sfo-temps [(->Temperature 10 "SFO")
                   (->Temperature 20 "SFO")]
        temp-rule (dsl/parse-rule [[?temps <- (acc/all) :from [Temperature (< temperature 25) (= ?location location)]]]
                                  (insert! (->TemperatureHistory (sort-by :temperature ?temps))))

        temp-history-query (dsl/parse-query [] [[TemperatureHistory (= ?temps temperatures)]])

        all-temps-session (-> (mk-session [temp-rule temp-history-query] :cache false)
                              (insert-all (concat mci-temps sfo-temps))
                              fire-rules)]

    (is (= (-> (apply retract all-temps-session mci-temps)
               fire-rules
               (query temp-history-query))
           [{:?temps []}]))))
````

However, it fails:

````
FAIL in (test-accum-all-with-bindings) (test_accumulators.clj:194)

expected: ({:?temps ()}
           {:?temps (#clara.rules.testfacts.Temperature {:location "SFO", :temperature 10}
                     #clara.rules.testfacts.Temperature {:location "SFO", :temperature 20})})
  actual: [{:?temps []}]

    diff: - [nil
             {:?temps (#clara.rules.testfacts.Temperature {:location "SFO", :temperature 10}
                       #clara.rules.testfacts.Temperature {:location "SFO", :temperature 20})}]
         
Ran 17 tests containing 42 assertions.
1 failures, 0 errors.
{:error 0, :fail 1, :pass 41, :test 17, :type :summary}
````

I believe the root cause of this is similar to that in [1], but it is
a slightly different problem so I decided to log it separately.  The difference
is that this case depends on what other bindings exist and the resolution of [2].
If, as discussed in [2], we want an accumulator with an initial value
to propagate, even with nil bindings, we probably only want one such
result to propagate, and then only in the absence of any real bindings.
Thus, when we retract all previous elements, whether we should propagate
nothing after retracting or the initial value with nil bindings depends
on if other binding groups are present.  In general, my thinking here
is that adding and retracting fact(s) or simply never inserting them
should both leave the session in the same ultimate state (excepting listeners of course).

I discovered this while writing tests for [3], but this is a separate concern
with the same behavior both before and after those changes.

1. https://github.com/rbrush/clara-rules/issues/188
2. https://github.com/rbrush/clara-rules/issues/102
3. https://github.com/rbrush/clara-rules/issues/182

**Comment by rbrush** [comment]
It seems like we'd want one accumulated value to propagate _per distinct set of bindings used by the accumulator_. So in this example, there would be a TemperatureHistory for all temps in MCI and another one for all temps in SFO, but there *would not* be a TemperatureHistory that is not associated with any city. (I think this is what I would expect as a user.) This aligns with the proposal I'm making in #102, where we wouldn't propagate the initial value if an accumulator's bindings cannot be satisfied.

This case is confusing because these test rules aren't really internally logical. It seems like I'd either want a TemperatureHistory grouped by city, or a TemperatureHistory of _everything_, but using the same TemperatureHistory fact for both seems confusing. If a user really wants that, an additional rule could be written that inserts TemperatureHistory if there are no Temperatures, or a user might better separate these concerns with separate TemperatureHistoryByCity and GlobalTemperatureHistory facts.

**Comment by WilliamParker** [comment]
The approach of ensuring that all variables are bound seems reasonable to me, and I agree with the assessment by @rbrush that a rule matching on nothing and one matching on groups of bindings is logically questionable, aside from any implementation concerns.  I can't think of any cases where firing with unbound bindings would be the best way to solve a problem.

I do see a complication to this though - how should should bindings that reflect explicit values of nil (or false, but we could just use a nil? check) be dealt with?  Wanting to propagate an actual result of nil in an accumulator, as discussed at https://github.com/rbrush/clara-rules/issues/182 , seems questionable to me.  However, having a field on a fact be nil and wanting to group on that seems like a plausible use-case.

**Comment by rbrush** [comment]
> I do see a complication to this though - how should should bindings that reflect explicit values of nil (or false, but we could just use a nil? check) be dealt with? Wanting to propagate an actual result of nil in an accumulator, as discussed at #182 , seems questionable to me. However, having a field on a fact be nil and wanting to group on that seems like a plausible use-case.

I think we can make this determination by seeing if the bindings map in the token has the expected key. So we wouldn't check for a non-nil value, we'd check to see if anything (including nil) was set in the bindings by an upstream expression.

**Comment by WilliamParker** [comment]
@mrrodriguez pointed out that I made a mistaken on my expectations in the test on the parent post since I missed the SFO group and included an empty group.  I believe the basic issue actually described in the text is correct though.  Revised test:

````
(deftest test-accum-all-with-bindings
  (let [mci-temps [(->Temperature 10 "MCI")
                   (->Temperature 20 "MCI")]
        sfo-temps [(->Temperature 10 "SFO")
                   (->Temperature 20 "SFO")]
        temp-rule (dsl/parse-rule [[?temps <- (acc/all) :from [Temperature (< temperature 25) (= ?location location)]]]
                                  (insert! (->TemperatureHistory (sort-by :temperature ?temps))))
 
        temp-history-query (dsl/parse-query [] [[TemperatureHistory (= ?temps temperatures)]])
 
        all-temps-session (-> (mk-session [temp-rule temp-history-query] :cache false)
                              (insert-all (concat mci-temps sfo-temps))
                              fire-rules)]
 
    (is (= (-> (apply retract all-temps-session mci-temps)
               fire-rules
               (query temp-history-query))
           [{:?temps [(->Temperature 10 "SFO") (->Temperature 20 "SFO")]}]))))
````

**Comment by mrrodriguez** [comment]
@rbrush @WilliamParker and anyone else.

The example posted here https://github.com/rbrush/clara-rules/issues/189#issuecomment-219848678 is clear to me that it should pass.  

However, there is still another case we haven't discussed and I am not a little shaky on.
This applies equally to AccumulateNode and AccumulateWithJoinFilterNode
```clj
(let [get-temp-history (dsl/parse-query [] [[?his <- TemperatureHistory]])
 
      get-temps=threshold (dsl/parse-rule [[?threshold <- :temp-threshold]
                                           [?temps <- (acc/all) :from [Temperature (= ?loc location)
                                                                       (= temperature (:temperature ?threshold))]]]
 
                                          (insert! (->TemperatureHistory ?temps)))
 
      thresh-10 ^{:type :temp-threshold} {:temperature 10}
      temp-10-mci (->Temperature 10 "MCI")
      temp-15-lax (->Temperature 15 "LAX")
        
      temp-history (-> (mk-session [get-temp-history get-temps=threshold])
                       (insert thresh-10)
                       (insert temp-10-mci
                               temp-15-lax)
                       (fire-rules)
                       (query get-temp-history))]
  (is (= 1 (count temp-history)))
  (is (= #{{:?his (->TemperatureHistory [temp-10-mci])}}
         (set temp-history))))
```

This is the behavior of AccumulateNode as of the changes from #190 .  However, AccumulateWithJoinFilterNode now differs.  I am working on AccumulateWithJoinFilterNode for this issue #189 as well as #188 currently and I noticed this.  We actually have tests that assert the behavior is this:
```clj
(is (= 2 (count temp-history)))
(is (= #{{:?his (->TemperatureHistory [temp-10-mci])}
         {:?his (->TemperatureHistory [])}}
       (set temp-history)))
```

The basic idea here is that there are facts inserted with different bindings, so they are grouped into multiple binding groups.  These facts are never retracted as in the example posted for this issue.  
Instead one of the binding groups satisfies the join condition criteria and the other group doesn't.


For bindings `?loc = "MCI"` there are facts meeting the join condition.  So we get an accumulated result for it.

However, there exists some facts with bindings `?loc = "LAX"`, but none of them meet the criteria of having `temperature` equal to the threshold.
So we do "know" that there is a binding group for "LAX" because there are facts with it.  However, none of these facts join to the required conditions.  Should we propagate the `:initial-value` for this "LAX" group anyways?

I am leaning towards the behavior of #190 introduced in AccumulateNode being correct.  Specifically, if no facts within a binding group can satisfy their conditions criteria, the `:initial-value` is *not* propagated.  The behavior would then be as if there were no "LAX" at all for this accumulator condition.  I think that is appropriate since none of the "LAX" that do exists, satisfy the condition.  So to me, that is almost like they don't exist because they could be "spurious" with respect to the condition actually being tested.

**Comment by rbrush** [comment]
> Specifically, if no facts within a binding group can satisfy their conditions criteria, the :initial-value is not propagated. 

So what would you expect for this query if there are no Temperature facts:

```cli
(defquery get-all-temps
 []
 [?all-temps <- (acc/all) :from [Temperature]]) 
```

I'd expect the query to match, but for ?all-temps to be an empty seq. If I'm reading your proposal correctly, then this wouldn't match? That seems a bit surprising to me, but might be worth it to be consistent with other behavior, like in your "LAX" example.

**Comment by mrrodriguez** [comment]
@rbrush I agree with you that  `get-all-temps` should propagate the empty collection.  That case is still fine and functional.

The question I had was more around the idea of having facts that match the accumulate node from a "class type" perspective, but fail to match any join or alpha node criteria/constraints.

To simplify my question perhaps, consider this easier case where there is only a single condition and no joins between conditions involved.
```clj
(let [q (dsl/parse-query [] [[?cs <- (acc/all) :from [Temperature (= ?loc location) (< temperature 10)]]])

      temp-9-mci (->Temperature 9 "MCI")
      temp-11-mci (->Temperature 11 "MCI")
      temp-11-lax (->Temperature 11 "LAX")

      mci-matches-lax-does-not (-> (mk-session [q])
                                   (insert temp-9-mci
                                           temp-11-lax)
                                   fire-rules
                                   (query q))

      neither-matches (-> (mk-session [q])
                          (insert temp-11-mci
                                  temp-11-lax)
                          fire-rules
                          (query q))]

  (is (= [{:?cs []}] neither-matches))
  (is (= [{:?cs [temp-9-mci] :?loc "MCI"}] mci-matches-lax-does-not)))
```

Specifically the 2nd `is` check.  This is the behavior I think is most expect here.  I wouldn't expect:
```clj
(is (= [{:?cs [temp-9-mci] :?loc "MCI"} {:?cs [] :?loc "LAX"}] mci-matches-lax-does-not))
```
The reason I wouldn't expect that is because there are no "LAX" facts that actually satisfy the criteria.  There are "MCI" though.  So we only have one "valid" binding group.  The other binding group is still an unknown since we don't even know that that "LAX" fact has any meaningful contribution to the rule since it doesn't satisfy the other criteria.  

This generalized to more binding groups too.  If we had facts for any number of locations -  "LAX", "MCI", "SFO", etc - and only "MCI" had any facts matching the `(< temperature 10)` constraint on the condition, I would only expect propagated results for "MCI".  
I wouldn't expect a bunch of `:initial-value` propagations for the other locations since they didn't have any real, meaningful matches to the `(< temperature 10)` constraint.

The overall theme I had with AccumulateNode aligns with this.  
* if **no binding group has any matching facts**, the `:initial-value` is **sent to all binding groups** 
* If **some binding group has matching facts**, the `:initial-value` is **not sent to any binding group** that doesn't have matches. 

(I'm going to just say "groups" instead of "binding groups" from here)

In this way the `:initial-value` serves as a value to propagate in the absence of any valid matches to all groups.  However, when real matches do happen, the `:initial-value` is not used anymore.

I think the overall topic is subtle and probably in a bit of a gray area as far as what "makes sense" in all cases.  However, I am still advocating for the behavior of non-matching groups not getting the `:initial-value` propagated when there are other groups with matches.

**Comment by rbrush** [comment]
Alright, that makes sense...and +1 for your proposal. It seems like the very nature accumulators with bindings is going to create something that's a bit surprising in some scenario, and I agree that it would seem odd to see a bunch of empty matches in the multi-binding group scenario.

**Comment by rbrush** [comment]
Is there anything left to do on this one? I know these got conflated with #188, #190 and #102, with an open edge case in #218. I think we can close this out and track #218 for anything more; let me know if that's incorrect.

**Comment by WilliamParker** [comment]
@rbrush I agree.  Closing.
