### ISSUE TITLE
Should AccumulateNode use the cat transducer instead of simple into call?

### ISSUE THREAD

**Issue by WilliamParker** [rbrush/clara-rules#211]
As discussed at [1] the changes to AccumulateWithJoinFilterNode at https://github.com/rbrush/clara-rules/pull/210 added to a collection like 

````
combined-candidates (into [] cat [previous-candidates candidates])
````
instead of 

````
(into previous-candidates candidates)
````

to avoid reordering.  AccumulateNode has something similar to this at [2]:

````
(let [.... combined (if has-previous? 
                                   (into previous facts) 
                                   facts)
````

In this case, since we use mapv at [3] and remove-first-of-each will return a vector now that the 1-element was removed in 210 [4], the empty case will return the original collection [5], and in any case the empty case will cause removal from the memory entirely [6], I think it works out correctly.  However, this all seems rather error-prone, and I'm skeptical that the probably low cost of creating an entirely new collection via a cat transducer versus using the (into previous facts) pattern is worth the risk of creating subtle bugs in the future.  I'm inclined to change that code in AccumulateNode to something like

````
(let [... combined (if has-previous?
                                  (into [] cat [previous facts])
                                  facts)]
````

Thoughts?  @rbrush @mrrodriguez 

Side note: I realize that the formatting in my Clojure code blocks is off above; if anyone knows how to get Github to do better formatting please let me know.  Formatting it correctly manually with spaces doesn't seem to work since GitHub rearranges it.

1. https://github.com/rbrush/clara-rules/pull/210#discussion_r74451191
2. https://github.com/rbrush/clara-rules/blob/e625710835f20b5bc243f18352948673b3c2f794/src/main/clojure/clara/rules/engine.cljc#L839
3. https://github.com/rbrush/clara-rules/blob/e625710835f20b5bc243f18352948673b3c2f794/src/main/clojure/clara/rules/engine.cljc#L821
4. https://github.com/rbrush/clara-rules/blob/e625710835f20b5bc243f18352948673b3c2f794/src/main/clojure/clara/rules/memory.cljc#L210
5. https://github.com/rbrush/clara-rules/blob/e625710835f20b5bc243f18352948673b3c2f794/src/main/clojure/clara/rules/memory.cljc#L205
6. https://github.com/rbrush/clara-rules/blob/e625710835f20b5bc243f18352948673b3c2f794/src/main/clojure/clara/rules/engine.cljc#L972

**Comment by mrrodriguez** [comment]
This change seems fine to me, but I think we are less prone to errors around this issue in AccumulateNode as we are in AccumulateWithJoinFilterNode.  The accumulated value is remembered in the AccumulateNode, it isn't re-derived in a way where it is critical to be sure the order of the facts stays the same from accumulation to accumulation.  Unless I'm missing something else to what you are saying, I don't think it tends to matter if the `combined` results come out in some sort of consistent or not here.

I'm still not opposed to a small change like this.  It always is good to keep things in order where it makes sense and isn't costly so that it is easier to follow and trust it won't mess things up in an way that is subtle to recreate.

**Comment by WilliamParker** [comment]
OK, after looking over it again I agree with @mrrodriguez .  The fact that we keep the previous value directly in AccumulateNode removes that risk.  It is a general point to be mindful of in any future accumulator changes, but I don't see a need to change this now.

I am closing this issue.
